stages:
  - trusty_verticenilavu

Ubuntu 14.04 verticenilavu:
  stage: trusty_verticenilavu
  script:
    - echo "$USER"
    - cd /home/gitlab-runner/builds/fc6c1713/0/megamsys/gitpackager/verticenilavu
    - rake clean
    - rake trusty
    - sudo cp -R /home/gitlab-runner/builds/fc6c1713/0/megamsys/gitpackager/verticenilavu/build/trusty/*.deb /home/megdc/deb
  allow_failure: true
  only:
    - 1.5.0-rc1
