stages:
  - trusty_nsq
  - trusty_nilavu
  - trusty_cadvisor
  - trusty_gateway
  - trusty_vertice
  - trusty_gulp
  - trusty_vnc
  - trusty_common
  - trusty_deploy
  - trusty_notification_slack
  - jessie_nsq
  - jessie_nilavu
  - jessie_cadvisor
  - jessie_gateway
  - jessie_vertice
  - jessie_gulp
  - jessie_vnc
  - jessie_common
  - jessie_deploy
  - jessie_notification_slack

Ubuntu 14.04 verticensqd:
  stage: trusty_nsq
  script:
    - echo "$USER"
    - cd /home/gitlab-runner/builds/fc6c1713/0/megamsys/gitpackager/verticensqd
    - rake clean
    - rake trusty
    - sudo cp -R /home/gitlab-runner/builds/fc6c1713/0/megamsys/gitpackager/verticensqd/build/trusty/*.deb /home/megdc/testing-1.5
  allow_failure: true
  only:
    - 1.5.0-rc1

Ubuntu 14.04 verticenilavu:
  stage: trusty_nilavu
  script:
    - echo "$USER"
    - cd /home/gitlab-runner/builds/fc6c1713/0/megamsys/gitpackager/verticenilavu
    - rake clean
    - rake trusty
    - sudo cp -R /home/gitlab-runner/builds/fc6c1713/0/megamsys/gitpackager/verticenilavu/build/trusty/*.deb /home/megdc/testing-1.5
  only:
    - 1.5.0-rc1
  allow_failure: true


Ubuntu 14.04 verticecadvisor:
  stage: trusty_cadvisor
  script:
    - echo "$USER"
    - cd /home/gitlab-runner/builds/fc6c1713/0/megamsys/gitpackager/verticecadvisor
    - rake clean
    - rake trusty
    - sudo cp -R /home/gitlab-runner/builds/fc6c1713/0/megamsys/gitpackager/verticecadvisor/build/trusty/*.deb /home/megdc/testing-1.5
  only:
    - 1.5.0-rc1
  allow_failure: true

Ubuntu 14.04 verticegateway:
  stage: trusty_gateway
  script:
    - echo "$USER"
    - cd /home/gitlab-runner/builds/fc6c1713/0/megamsys/gitpackager/verticegateway
    - rake clean
    - rake trusty
    - sudo cp -R /home/gitlab-runner/builds/fc6c1713/0/megamsys/gitpackager/verticegateway/build/trusty/vertice_gateway/target/*.deb /home/megdc/testing-1.5
  only:
    - 1.5.0-rc1
  allow_failure: true

Ubuntu 14.04 vertice:
  stage: trusty_vertice
  before_script:
    - echo "$USER"
    - export GOPATH=/home/gitlab-runner/.go
    - export GOROOT=/home/gitlab-runner/software/go
    - export PATH="$PATH:$HOME/.rvm/bin:$GOROOT/bin:$GOPATH/bin"
  script:
    - cd /home/gitlab-runner/builds/fc6c1713/0/megamsys/gitpackager/vertice
    - rake clean
    - echo "$USER"
    - rake trusty
    - sudo cp -R /home/gitlab-runner/builds/fc6c1713/0/megamsys/gitpackager/vertice/build/trusty/*.deb /home/megdc/testing-1.5
  only:
    - 1.5.0-rc1
  allow_failure: true

Ubuntu 14.04 verticegulpd:
  stage: trusty_gulp
  before_script:
    - echo "$USER"
    - export GOPATH=/home/gitlab-runner/.go
    - export GOROOT=/home/gitlab-runner/software/go
    - export PATH="$PATH:$HOME/.rvm/bin:$GOROOT/bin:$GOPATH/bin"
  script:
    - cd /home/gitlab-runner/builds/fc6c1713/0/megamsys/gitpackager/verticegulpd
    - rake clean
    - echo "$USER"
    - rake trusty
    - sudo cp -R /home/gitlab-runner/builds/fc6c1713/0/megamsys/gitpackager/verticegulpd/build/trusty/*.deb /home/megdc/testing-1.5
  only:
    - 1.5.0-rc1
  allow_failure: true

Ubuntu 14.04 verticevnc:
  stage: trusty_vnc
  script:
    - echo "$USER"
    - cd /home/gitlab-runner/builds/fc6c1713/0/megamsys/gitpackager/verticevnc
    - rake clean
    - rake trusty
    - sudo cp -R /home/gitlab-runner/builds/fc6c1713/0/megamsys/gitpackager/verticevnc/build/trusty/*.deb /home/megdc/testing-1.5
  only:
    - 1.5.0-rc1
  allow_failure: true

Ubuntu 14.04 verticecommon:
  stage: trusty_common
  script:
    - echo "$USER"
    - cd /home/gitlab-runner/builds/fc6c1713/0/megamsys/gitpackager/verticecommon
    - rake clean
    - rake trusty
    - sudo cp -R /home/gitlab-runner/builds/fc6c1713/0/megamsys/gitpackager/verticecommon/build/trusty/*.deb /home/megdc/testing-1.5
  only:
    - 1.5.0-rc1
  allow_failure: true

Ubuntu 14.04 deploy:
  stage: trusty_deploy
  script:
    - echo "$USER"
    - cd /home/megdc
    - ./reprepro-new.sh version=1.5 distro=trusty release=testing
  allow_failure: true


notify:slack:
  stage: trusty_notification_slack
  before_script:
    - sudo apt-get update && sudo apt-get install -y git curl bash
  script:
    - ./support/notify_slack "#relengg" "Ubuntu Trusty Build on \`$CI_BUILD_REF_NAME\` success! Commit \`$(git log -1 --oneline)\` See <https://gitlab.com/megamsys/gitpackager/commit/"$CI_BUILD_REF"/builds>"
  #when: on_success
  only:
    - 1.5.0-rc1

Jessie verticensqd:
  stage: jessie_nsq
  script:
    - echo "$USER"
    - cd /home/gitlab-runner/builds/fc6c1713/0/megamsys/gitpackager/verticensqd
    - rake clean
    - rake jessie
    - sudo cp -R /home/gitlab-runner/builds/fc6c1713/0/megamsys/gitpackager/verticensqd/build/trusty/*.deb /home/megdc/jessie
  allow_failure: true
  only:
    - 1.5.0-rc1

Jessie verticenilavu:
  stage: jessie_nilavu
  script:
    - echo "$USER"
    - cd /home/gitlab-runner/builds/fc6c1713/0/megamsys/gitpackager/verticenilavu
    - rake clean
    - rake jessie
    - sudo cp -R /home/gitlab-runner/builds/fc6c1713/0/megamsys/gitpackager/verticenilavu/build/trusty/*.deb /home/megdc/jessie
  only:
    - 1.5.0-rc1
  allow_failure: true


Jessie verticecadvisor:
  stage: jessie_cadvisor
  script:
    - echo "$USER"
    - cd /home/gitlab-runner/builds/fc6c1713/0/megamsys/gitpackager/verticecadvisor
    - rake clean
    - rake jessie
    - sudo cp -R /home/gitlab-runner/builds/fc6c1713/0/megamsys/gitpackager/verticecadvisor/build/trusty/*.deb /home/megdc/jessie
  only:
    - 1.5.0-rc1
  allow_failure: true

Jessie verticegateway:
  stage: jessie_gateway
  script:
    - echo "$USER"
    - cd /home/gitlab-runner/builds/fc6c1713/0/megamsys/gitpackager/verticegateway
    - rake clean
    - rake jessie
    - sudo cp -R /home/gitlab-runner/builds/fc6c1713/0/megamsys/gitpackager/verticegateway/build/trusty/vertice_gateway/target/*.deb /home/megdc/jessie
  only:
    - 1.5.0-rc1
  allow_failure: true

Jessie vertice:
  stage: jessie_vertice
  before_script:
    - echo "$USER"
    - export GOPATH=/home/gitlab-runner/.go
    - export GOROOT=/home/gitlab-runner/software/go
    - export PATH="$PATH:$HOME/.rvm/bin:$GOROOT/bin:$GOPATH/bin"
  script:
    - cd /home/gitlab-runner/builds/fc6c1713/0/megamsys/gitpackager/vertice
    - rake clean
    - echo "$USER"
    - rake jessie
    - sudo cp -R /home/gitlab-runner/builds/fc6c1713/0/megamsys/gitpackager/vertice/build/trusty/*.deb /home/megdc/jessie
  only:
    - 1.5.0-rc1
  allow_failure: true

Jessie verticegulpd:
  stage: jessie_gulp
  before_script:
    - echo "$USER"
    - export GOPATH=/home/gitlab-runner/.go
    - export GOROOT=/home/gitlab-runner/software/go
    - export PATH="$PATH:$HOME/.rvm/bin:$GOROOT/bin:$GOPATH/bin"
  script:
    - cd /home/gitlab-runner/builds/fc6c1713/0/megamsys/gitpackager/verticegulpd
    - rake clean
    - echo "$USER"
    - rake jessie
    - sudo cp -R /home/gitlab-runner/builds/fc6c1713/0/megamsys/gitpackager/verticegulpd/build/trusty/*.deb /home/megdc/jessie
  only:
    - 1.5.0-rc1
  allow_failure: true

Jessie verticevnc:
  stage: jessie_vnc
  script:
    - echo "$USER"
    - cd /home/gitlab-runner/builds/fc6c1713/0/megamsys/gitpackager/verticevnc
    - rake clean
    - rake jessie
    - sudo cp -R /home/gitlab-runner/builds/fc6c1713/0/megamsys/gitpackager/verticevnc/build/trusty/*.deb /home/megdc/jessie
  only:
    - 1.5.0-rc1
  allow_failure: true

Jessie verticecommon:
  stage: jessie_common
  script:
    - echo "$USER"
    - cd /home/gitlab-runner/builds/fc6c1713/0/megamsys/gitpackager/verticecommon
    - rake clean
    - rake jessie
    - sudo cp -R /home/gitlab-runner/builds/fc6c1713/0/megamsys/gitpackager/verticecommon/build/trusty/*.deb /home/megdc/jessie
  only:
    - 1.5.0-rc1
  allow_failure: true

Jessie deploy:
  stage: jessie_deploy
  script:
    - echo "$USER"
    - cd /home/megdc
    - ./reprepro-new.sh version=1.5 distro=jessie release=testing
  allow_failure: true


Jessie notify:slack:
  stage: jessie_notification_slack
  before_script:
    - sudo apt-get update && sudo apt-get install -y git curl bash
  script:
    - ./support/notify_slack "#relengg" "Jessie  Build on \`$CI_BUILD_REF_NAME\` success! Commit \`$(git log -1 --oneline)\` See <https://gitlab.com/megamsys/gitpackager/commit/"$CI_BUILD_REF"/builds>"
  #when: on_success
  only:
    - 1.5.0-rc1
